package com.yuxiu.edu.model;

public class User1 {
    public User1(Integer username, Integer tel, Integer email, Integer qq, Integer alipay, Integer name, Integer amount, Integer balance, Integer register) {
        this.username = username;
        this.tel = tel;
        this.email = email;
        this.qq = qq;
        this.alipay = alipay;
        this.name = name;
        this.amount = amount;
        this.balance = balance;
        this.register = register;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.username
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.tel
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.email
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.qq
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.alipay
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer alipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.name
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.amount
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.balance
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user1.register
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    private Integer register;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.username
     *
     * @return the value of t_user1.username
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.username
     *
     * @param username the value for t_user1.username
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setUsername(Integer username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.tel
     *
     * @return the value of t_user1.tel
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.tel
     *
     * @param tel the value for t_user1.tel
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setTel(Integer tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.email
     *
     * @return the value of t_user1.email
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.email
     *
     * @param email the value for t_user1.email
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setEmail(Integer email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.qq
     *
     * @return the value of t_user1.qq
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.qq
     *
     * @param qq the value for t_user1.qq
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.alipay
     *
     * @return the value of t_user1.alipay
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.alipay
     *
     * @param alipay the value for t_user1.alipay
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setAlipay(Integer alipay) {
        this.alipay = alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.name
     *
     * @return the value of t_user1.name
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.name
     *
     * @param name the value for t_user1.name
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setName(Integer name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.amount
     *
     * @return the value of t_user1.amount
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.amount
     *
     * @param amount the value for t_user1.amount
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.balance
     *
     * @return the value of t_user1.balance
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.balance
     *
     * @param balance the value for t_user1.balance
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user1.register
     *
     * @return the value of t_user1.register
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public Integer getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user1.register
     *
     * @param register the value for t_user1.register
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    public void setRegister(Integer register) {
        this.register = register;
    }
}