package com.yuxiu.edu.mapper;

import com.yuxiu.edu.model.User1;
import com.yuxiu.edu.model.User1Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    int countByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    int deleteByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    int insert(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    int insertSelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    List<User1> selectByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user1
     *
     * @mbggenerated Thu Aug 08 09:06:29 CST 2019
     */
    int updateByExample(@Param("record") User1 record, @Param("example") User1Example example);
}